# Generated by Django 2.0 on 2017-12-11 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171211_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soldiers', to='api.Squad'),
        ),
    ]
