# Generated by Django 2.0 on 2017-12-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171211_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='role',
            field=models.CharField(choices=[('COMMANDER', 'Commander'), ('GUNNER', 'Gunner'), ('MARKSMAN', 'Marksman'), ('GRUNT', 'Grunt')], default='GRUNT', max_length=100),
        ),
    ]
