# Generated by Django 2.0 on 2017-12-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171211_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='role',
            field=models.CharField(choices=[('Commander', 'Commander'), ('Gunner', 'Gunner'), ('Marksman', 'Marksman'), ('Grunt', 'Grunt')], default='Grunt', max_length=100),
        ),
    ]
